### ISSUE TITLE
YT short on anchor-scope

### ISSUE THREAD

**Issue by jamesnw** [oddbird/oddleventy#738]
https://www.youtube.com/shorts/F4x4iyUscH0

**Comment by jamesnw** [comment]
`anchor-scope` is out in Chromium 131, and unlocks a lot of use cases. Here's an explainer in less than a minute.
(Oh, and you can use it now with OddBird's Anchor Positioning Polyfill).

**Comment by SondraE** [comment]
Could this video have a thumbnail like the CSS Anchor Position Polyfill short @stacyk made, to help connect them visually? https://www.youtube.com/shorts/CAPa_tGHlC8

At the end of the video, could you also a display a link to the Anchor Positioning repo or something similar (whatever is short and makes sense) so that the links aren't buried in the description? It would also be nice if, after inviting people to use anchor-scope, you said something like, "join and sponsor this work on GitHub at Awesome Anchor Positioning."

Also, when I was doing a bit of reading about marketing for YT Shorts, people suggested including a CTA and link in with the title because that automatically shows up for all viewers whereas the description is mostly hidden.

**Comment by SondraE** [comment]
@jamesnw Great!

**Comment by jamesnw** [comment]
> @jamesnw Do you want to go ahead and publish this and add it to the Anchor Positioning YT playlist, or are you okay if I do? I'd like to mention it in OddNews.

I'll try to make it live and promote it Thursday AM, but if I don't, feel free to do it.

**Comment by jamesnw** [comment]
Published and promoted-

https://bsky.app/profile/jamessw.com/post/3lavz3w34qk2o
https://front-end.social/@jamessw/113481635698963615
